# Generated by Django 5.1.1 on 2024-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_version',
            field=models.IntegerField(help_text='Введите номер версии', unique=True, verbose_name='Номер версии'),
        ),
    ]
