# Generated by Django 5.1.1 on 2024-10-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0003_alter_product_number_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.FloatField(
                        help_text="Введите номер версии",
                        unique=True,
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "name_version",
                    models.CharField(
                        help_text="Введите название версии",
                        max_length=100,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Укажите текущая это версия или нет",
                        verbose_name="Текущая версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["number_version", "name_version"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "number_version"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_version",
        ),
        migrations.AlterField(
            model_name="product",
            name="number_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите номер версии",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="version",
                to="catalog_2.version",
                verbose_name="Номер версии",
            ),
        ),
    ]
