# Generated by Django 5.1.1 on 2024-10-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0004_version_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="number_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите номер версии",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog_2.version",
                verbose_name="Номер версии",
            ),
        ),
    ]
