# Generated by Django 4.2.2 on 2024-10-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0009_category_product_is_active_alter_version_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
