# Generated by Django 4.2.2 on 2024-10-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0010_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_is_active", "Can edit is_active"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
