# Generated by Django 4.2.2 on 2024-10-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0011_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания продукта в базе данных"
            ),
        ),
    ]
