# Generated by Django 4.2.2 on 2024-10-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_2", "0012_alter_product_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="user_product",
        ),
    ]
